#!/bin/bash

function log() {
    echo $@ 1>&2
    $@
}

log $CROWC test.cr --dump-asm >test.s || exit 1
as test.s -o test.o || exit 1
log gcc testc.c -c -o testc.o || exit 1
log gcc testc.o test.o -o test || exit 1
./test || exit 1