#!/bin/bash

function log() {
    echo $@ 1>&2
    $@
}

log "$CROWC" test.cr -c -o test.s || exit 1
log as test.s -o test.o || exit 1
log gcc "-I$FSROOT/include/crow" testc.c -c -o testc.o || exit 1
log "$CROWL" testc.o test.o -o test || exit 1
./test || exit 1